[2022-08-13 02:17:44,005] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-12T00:00:00+00:00 [queued]>
[2022-08-13 02:17:44,027] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-12T00:00:00+00:00 [queued]>
[2022-08-13 02:17:44,028] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 02:17:44,028] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-13 02:17:44,029] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 02:17:44,056] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-08-12 00:00:00+00:00
[2022-08-13 02:17:44,068] {standard_task_runner.py:52} INFO - Started process 3028 to run task
[2022-08-13 02:17:44,087] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-08-12T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpc8pornzz', '--error-file', '/tmp/tmpd1e3aro_']
[2022-08-13 02:17:44,099] {standard_task_runner.py:80} INFO - Job 173: Subtask model_dag
[2022-08-13 02:17:44,326] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-08-12T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-13 02:17:44,565] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-12T00:00:00+00:00
[2022-08-13 02:18:25,546] {python.py:173} INFO - Done. Returned value was: None
[2022-08-13 02:18:25,560] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220812T000000, start_date=20220813T021744, end_date=20220813T021825
[2022-08-13 02:18:25,621] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-13 02:18:25,653] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
