[2022-08-02 01:43:49,433] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-07-31T00:00:00+00:00 [queued]>
[2022-08-02 01:43:49,447] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-07-31T00:00:00+00:00 [queued]>
[2022-08-02 01:43:49,448] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 01:43:49,448] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-02 01:43:49,448] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 01:43:49,465] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-07-31 00:00:00+00:00
[2022-08-02 01:43:49,471] {standard_task_runner.py:52} INFO - Started process 6371 to run task
[2022-08-02 01:43:49,474] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-07-31T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpbxgodaih', '--error-file', '/tmp/tmpf3gjuul4']
[2022-08-02 01:43:49,475] {standard_task_runner.py:80} INFO - Job 102: Subtask model_dag
[2022-08-02 01:43:49,558] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-07-31T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-02 01:43:49,694] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-07-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-31T00:00:00+00:00
[2022-08-02 01:44:31,466] {python.py:173} INFO - Done. Returned value was: None
[2022-08-02 01:44:31,480] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220731T000000, start_date=20220802T014349, end_date=20220802T014431
[2022-08-02 01:44:31,534] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-02 01:44:31,562] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
