[2022-08-28 00:00:02,181] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.yr_mk_price_dag scheduled__2022-08-27T00:00:00+00:00 [queued]>
[2022-08-28 00:00:02,189] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.yr_mk_price_dag scheduled__2022-08-27T00:00:00+00:00 [queued]>
[2022-08-28 00:00:02,189] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 00:00:02,189] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-28 00:00:02,190] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 00:00:02,203] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): yr_mk_price_dag> on 2022-08-27 00:00:00+00:00
[2022-08-28 00:00:02,208] {standard_task_runner.py:52} INFO - Started process 11877 to run task
[2022-08-28 00:00:02,210] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'yr_mk_price_dag', 'scheduled__2022-08-27T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmph59u7mrm', '--error-file', '/tmp/tmpvzc0uudu']
[2022-08-28 00:00:02,211] {standard_task_runner.py:80} INFO - Job 266: Subtask yr_mk_price_dag
[2022-08-28 00:00:02,267] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.yr_mk_price_dag scheduled__2022-08-27T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-28 00:00:02,429] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=yr_mk_price_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-27T00:00:00+00:00
[2022-08-28 00:00:42,564] {python.py:173} INFO - Done. Returned value was: None
[2022-08-28 00:00:42,574] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=yr_mk_price_dag, execution_date=20220827T000000, start_date=20220828T000002, end_date=20220828T000042
[2022-08-28 00:00:42,586] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-28 00:00:42,588] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 11877. PIDs of all processes in the group: [11877]
[2022-08-28 00:00:42,588] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 11877
[2022-08-28 00:00:42,592] {process_utils.py:75} INFO - Process psutil.Process(pid=11877, status='terminated', exitcode=0, started='00:00:02') (11877) terminated with exit code 0
