[2022-08-05 19:07:08,655] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 19:07:08,675] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 19:07:08,675] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 19:07:08,676] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-05 19:07:08,676] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 19:07:08,708] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-08-04 00:00:00+00:00
[2022-08-05 19:07:08,717] {standard_task_runner.py:52} INFO - Started process 7187 to run task
[2022-08-05 19:07:08,723] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpupitros6', '--error-file', '/tmp/tmpcfm_x79j']
[2022-08-05 19:07:08,725] {standard_task_runner.py:80} INFO - Job 125: Subtask model_dag
[2022-08-05 19:07:08,888] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-08-04T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-05 19:07:09,099] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-04T00:00:00+00:00
[2022-08-05 19:07:56,912] {python.py:173} INFO - Done. Returned value was: None
[2022-08-05 19:07:56,929] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220804T000000, start_date=20220805T190708, end_date=20220805T190756
[2022-08-05 19:07:56,979] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-05 19:07:57,013] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
