[2022-08-30 00:30:25,657] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 00:30:25,673] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 00:30:25,674] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 00:30:25,674] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-30 00:30:25,675] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 00:30:25,701] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-08-29 00:00:00+00:00
[2022-08-30 00:30:25,710] {standard_task_runner.py:52} INFO - Started process 25412 to run task
[2022-08-30 00:30:25,715] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmp62y6l9rb', '--error-file', '/tmp/tmp7ysqnio0']
[2022-08-30 00:30:25,716] {standard_task_runner.py:80} INFO - Job 282: Subtask model_dag
[2022-08-30 00:30:25,812] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-08-29T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-30 00:30:25,902] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2022-08-30 00:31:14,695] {python.py:173} INFO - Done. Returned value was: None
[2022-08-30 00:31:14,708] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220829T000000, start_date=20220830T003025, end_date=20220830T003114
[2022-08-30 00:31:14,739] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-30 00:31:14,771] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
