[2022-09-02 00:08:04,722] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-02 00:08:04,736] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-02 00:08:04,736] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 00:08:04,737] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-02 00:08:04,738] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 00:08:04,757] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-09-01 00:00:00+00:00
[2022-09-02 00:08:04,764] {standard_task_runner.py:52} INFO - Started process 28015 to run task
[2022-09-02 00:08:04,768] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpu3lj6pds', '--error-file', '/tmp/tmp0sjp0yo3']
[2022-09-02 00:08:04,769] {standard_task_runner.py:80} INFO - Job 302: Subtask model_dag
[2022-09-02 00:08:04,851] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-09-01T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-09-02 00:08:04,976] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-02 00:08:51,422] {python.py:173} INFO - Done. Returned value was: None
[2022-09-02 00:08:51,438] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220901T000000, start_date=20220902T000804, end_date=20220902T000851
[2022-09-02 00:08:51,474] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-02 00:08:51,518] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
