[2022-08-22 02:32:15,938] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-18T00:00:00+00:00 [queued]>
[2022-08-22 02:32:16,007] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-18T00:00:00+00:00 [queued]>
[2022-08-22 02:32:16,008] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 02:32:16,012] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-22 02:32:16,013] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 02:32:16,079] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-08-18 00:00:00+00:00
[2022-08-22 02:32:16,124] {standard_task_runner.py:52} INFO - Started process 17353 to run task
[2022-08-22 02:32:16,140] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-08-18T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpgtwqryzi', '--error-file', '/tmp/tmpq6bh37g3']
[2022-08-22 02:32:16,164] {standard_task_runner.py:80} INFO - Job 220: Subtask model_dag
[2022-08-22 02:32:16,537] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-08-18T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-22 02:32:16,816] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-18T00:00:00+00:00
[2022-08-22 02:33:15,216] {python.py:173} INFO - Done. Returned value was: None
[2022-08-22 02:33:15,236] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220818T000000, start_date=20220822T023215, end_date=20220822T023315
[2022-08-22 02:33:15,295] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-22 02:33:15,338] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
