[2022-08-06 03:38:44,493] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.link_dag scheduled__2022-08-05T00:00:00+00:00 [queued]>
[2022-08-06 03:38:44,507] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.link_dag scheduled__2022-08-05T00:00:00+00:00 [queued]>
[2022-08-06 03:38:44,508] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 03:38:44,508] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-06 03:38:44,509] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 03:38:44,533] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): link_dag> on 2022-08-05 00:00:00+00:00
[2022-08-06 03:38:44,542] {standard_task_runner.py:52} INFO - Started process 9403 to run task
[2022-08-06 03:38:44,546] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'link_dag', 'scheduled__2022-08-05T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmp2rluy0rc', '--error-file', '/tmp/tmplgqm4h4g']
[2022-08-06 03:38:44,547] {standard_task_runner.py:80} INFO - Job 134: Subtask link_dag
[2022-08-06 03:38:44,645] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.link_dag scheduled__2022-08-05T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-06 03:38:44,740] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=link_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-05T00:00:00+00:00
[2022-08-06 03:39:28,242] {python.py:173} INFO - Done. Returned value was: None
[2022-08-06 03:39:28,257] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=link_dag, execution_date=20220805T000000, start_date=20220806T033844, end_date=20220806T033928
[2022-08-06 03:39:28,294] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 03:39:28,336] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
