[2022-08-09 03:19:48,699] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.link_dag scheduled__2022-08-07T00:00:00+00:00 [queued]>
[2022-08-09 03:19:48,724] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.link_dag scheduled__2022-08-07T00:00:00+00:00 [queued]>
[2022-08-09 03:19:48,725] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 03:19:48,726] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-09 03:19:48,727] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 03:19:48,768] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): link_dag> on 2022-08-07 00:00:00+00:00
[2022-08-09 03:19:48,783] {standard_task_runner.py:52} INFO - Started process 10140 to run task
[2022-08-09 03:19:48,788] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'link_dag', 'scheduled__2022-08-07T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmp66nck39m', '--error-file', '/tmp/tmp142qom4u']
[2022-08-09 03:19:48,790] {standard_task_runner.py:80} INFO - Job 148: Subtask link_dag
[2022-08-09 03:19:48,961] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.link_dag scheduled__2022-08-07T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-09 03:19:49,160] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=link_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-07T00:00:00+00:00
[2022-08-09 03:20:32,969] {python.py:173} INFO - Done. Returned value was: None
[2022-08-09 03:20:32,984] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=link_dag, execution_date=20220807T000000, start_date=20220809T031948, end_date=20220809T032032
[2022-08-09 03:20:33,011] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-09 03:20:33,055] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
