[2022-09-03 17:03:52,287] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-09-02T00:00:00+00:00 [queued]>
[2022-09-03 17:03:52,305] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-09-02T00:00:00+00:00 [queued]>
[2022-09-03 17:03:52,305] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 17:03:52,306] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-03 17:03:52,306] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 17:03:52,333] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-09-02 00:00:00+00:00
[2022-09-03 17:03:52,341] {standard_task_runner.py:52} INFO - Started process 12659 to run task
[2022-09-03 17:03:52,345] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-09-02T00:00:00+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpti219rt0', '--error-file', '/tmp/tmp9wgb6kq2']
[2022-09-03 17:03:52,346] {standard_task_runner.py:80} INFO - Job 312: Subtask model_dag
[2022-09-03 17:03:52,442] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-09-02T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-09-03 17:03:52,569] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-02T00:00:00+00:00
[2022-09-03 17:04:39,292] {python.py:173} INFO - Done. Returned value was: None
[2022-09-03 17:04:39,318] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220902T000000, start_date=20220903T170352, end_date=20220903T170439
[2022-09-03 17:04:39,365] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-03 17:04:39,443] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
