[2022-08-31 00:48:33,678] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-30T00:00:00+00:00 [queued]>
[2022-08-31 00:48:33,698] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-30T00:00:00+00:00 [queued]>
[2022-08-31 00:48:33,699] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 00:48:33,699] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-31 00:48:33,700] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 00:48:33,738] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-08-30 00:00:00+00:00
[2022-08-31 00:48:33,749] {standard_task_runner.py:52} INFO - Started process 1662 to run task
[2022-08-31 00:48:33,754] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-08-30T00:00:00+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpuj0hyyzr', '--error-file', '/tmp/tmp652mu8v_']
[2022-08-31 00:48:33,756] {standard_task_runner.py:80} INFO - Job 289: Subtask model_dag
[2022-08-31 00:48:33,876] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-08-30T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-31 00:48:34,032] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-30T00:00:00+00:00
[2022-08-31 00:49:21,399] {python.py:173} INFO - Done. Returned value was: None
[2022-08-31 00:49:21,418] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220830T000000, start_date=20220831T004833, end_date=20220831T004921
[2022-08-31 00:49:21,465] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-31 00:49:21,519] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
