[2022-08-22 02:32:15,585] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.link_dag scheduled__2022-08-21T00:00:00+00:00 [queued]>
[2022-08-22 02:32:15,648] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.link_dag scheduled__2022-08-21T00:00:00+00:00 [queued]>
[2022-08-22 02:32:15,649] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 02:32:15,650] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-22 02:32:15,655] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 02:32:15,739] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): link_dag> on 2022-08-21 00:00:00+00:00
[2022-08-22 02:32:15,763] {standard_task_runner.py:52} INFO - Started process 17350 to run task
[2022-08-22 02:32:15,782] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'link_dag', 'scheduled__2022-08-21T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpe1tkrbwg', '--error-file', '/tmp/tmpnou1rk8z']
[2022-08-22 02:32:15,788] {standard_task_runner.py:80} INFO - Job 216: Subtask link_dag
[2022-08-22 02:32:16,070] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.link_dag scheduled__2022-08-21T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-22 02:32:16,712] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=link_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T00:00:00+00:00
[2022-08-22 02:33:13,794] {python.py:173} INFO - Done. Returned value was: None
[2022-08-22 02:33:13,810] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=link_dag, execution_date=20220821T000000, start_date=20220822T023215, end_date=20220822T023313
[2022-08-22 02:33:13,876] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-22 02:33:13,927] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
