[2022-08-09 03:19:48,931] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-08T00:00:00+00:00 [queued]>
[2022-08-09 03:19:48,964] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-08-08T00:00:00+00:00 [queued]>
[2022-08-09 03:19:48,965] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 03:19:48,966] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-09 03:19:48,967] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 03:19:49,012] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-08-08 00:00:00+00:00
[2022-08-09 03:19:49,036] {standard_task_runner.py:52} INFO - Started process 10145 to run task
[2022-08-09 03:19:49,043] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-08-08T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpna1sccww', '--error-file', '/tmp/tmp743owrpn']
[2022-08-09 03:19:49,046] {standard_task_runner.py:80} INFO - Job 151: Subtask model_dag
[2022-08-09 03:19:49,196] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-08-08T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-08-09 03:19:49,335] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-08-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-08T00:00:00+00:00
[2022-08-09 03:20:33,811] {python.py:173} INFO - Done. Returned value was: None
[2022-08-09 03:20:33,829] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220808T000000, start_date=20220809T031948, end_date=20220809T032033
[2022-08-09 03:20:33,881] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-09 03:20:33,924] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
