[2022-07-29 03:44:08,253] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-07-28T00:00:00+00:00 [queued]>
[2022-07-29 03:44:08,261] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.model_dag scheduled__2022-07-28T00:00:00+00:00 [queued]>
[2022-07-29 03:44:08,262] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 03:44:08,262] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-29 03:44:08,264] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 03:44:08,282] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): model_dag> on 2022-07-28 00:00:00+00:00
[2022-07-29 03:44:08,288] {standard_task_runner.py:52} INFO - Started process 25896 to run task
[2022-07-29 03:44:08,291] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'model_dag', 'scheduled__2022-07-28T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpxytpoii3', '--error-file', '/tmp/tmpmme769ye']
[2022-07-29 03:44:08,292] {standard_task_runner.py:80} INFO - Job 84: Subtask model_dag
[2022-07-29 03:44:08,360] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.model_dag scheduled__2022-07-28T00:00:00+00:00 [running]> on host 36e1df4dd6ce
[2022-07-29 03:44:08,440] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=model_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-28T00:00:00+00:00
[2022-07-29 03:44:48,903] {python.py:173} INFO - Done. Returned value was: None
[2022-07-29 03:44:48,917] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=csv_dag, task_id=model_dag, execution_date=20220728T000000, start_date=20220729T034408, end_date=20220729T034448
[2022-07-29 03:44:48,942] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-29 03:44:48,979] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
